modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="synthbooksmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SynthBooks Mod" #mandatory
logoFile="examplemod.png" #optional
credits="A simple mod by Anthony" #optional
authors="Anthony" #optional
description='''
A new way to make books. That's all.
'''
[[dependencies.synthbooksmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.synthbooksmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
